---
# This playbook deploys the web boxes one at a time
# Pulls them out of load balancer before
# and puts them back afterwards

- name: setup web box
  hosts: webservers
  serial: 1
  become: yes
  become_method: sudo

  # basic pre_task and post_task example
  pre_tasks:
  - name: Gathering ec2 facts
    action: ec2_facts
  - name: Instance De-register
    become: no
    local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      region: us-west-1
      state: 'absent'

  roles:
  - common
  - web

  post_tasks:
  - name: Instance Register
    become: no
    local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      region: us-west-1
      ec2_elbs: "{{ item }}"
      state: 'present'
    with_items: ec2_elbs
