---
# This playbook deploys the whole application stack in this site.

- name: setup local machine
  hosts: localhost

  roles:
  - local

- name: install docker
  hosts: remotehosts
  become: yes
  become_method: sudo

  roles:
    - common

- include: start_site_local.yml
- include: db_migrate.yml
