---
# pull down docker-web and start it

- name: destroy the previous web
  docker:
    name: web
    state: absent #stops and then removes any matching containers.
    image: asksonar/docker-web:latest

- name: pull down and load docker-web
  docker:
    name: web
    hostname: web
    image: asksonar/docker-web:latest
    state: restarted #unconditionally restarts (or starts) the matching containers
    pull: always #the registry will be checked for a newer version of the image' each time the task executes
    env:
      DATABASE_URL: "postgres://postgres@{{db_host}}:5432/postgres"
      SECRET_KEY_BASE: bd75f41c7a4684b94f4ef0cafceb0966293a5b43c2dcf3bed76bbe085c0ec0ea58392ecfdd72f341ef3ea558d8fe3b86bd61bb15955302c675acc8b5fa073823
    volumes:
    - /var/src/web:/home/app/webapp
    ports:
    - "80:80"
    - "443:443"
