---
# pull down docker-web and start it

- name: add insecure registry
  lineinfile: >
    dest=/etc/default/docker regexp='DOCKER_OPTS' line='DOCKER_OPTS="--insecure-registry jenkins.engsonar.com:5000"' state=present

- name: restart docker
# pending this fix - https://github.com/ansible/ansible-modules-core/issues/1170
#  service: name=docker state=restarted
  shell: service docker restart

- name: add papertrail forwarding via logspout
  docker:
    name: logspout
    hostname: "{{ ansible_hostname }}"
    image: gliderlabs/logspout
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    command: syslog://logs3.papertrailapp.com:19980

- name: destroy the previous web
  docker:
    name: web
    state: absent #stops and then removes any matching containers.
    image: jenkins.engsonar.com:5000/web:latest

# broken up version of command
# docker rmi $(docker images -qf "dangling=true")
- name: get list of old docker images
  shell: docker images -qf "dangling=true"
  register: dangling_images

# performs no action if previous command generates no lines
# will fail if image is in use by container
# manually cleaning up such cases is preferred to telling ansible to ignore_errors
- name: remove old docker images
  shell: docker rmi {{item}}
  with_items: dangling_images.stdout_lines

- name: pull down and load docker-web
  docker:
    name: web
    hostname: web
    registry: jenkins.engsonar.com:5000
    insecure_registry: true
    image: jenkins.engsonar.com:5000/web:latest
    state: restarted #unconditionally restarts (or starts) the matching containers
    pull: always #the registry will be checked for a newer version of the image' each time the task executes
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/log
    env:
      RACK_ENV: production
      RAILS_ENV: production
      SONAR_ENV: "{{ sonar_env }}"
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      DATABASE_URL: "{{ database_url }}"
      RAILS_RESQUE_REDIS: "{{ rails_resque_redis }}"
    command: /sbin/my_init -- sh -c '/etc/my_startup/start_thin.sh'
