---
# pull down docker-web and start it

- name: add insecure registry
  lineinfile: >
    dest=/etc/default/docker regexp='DOCKER_OPTS' line='DOCKER_OPTS="--insecure-registry jenkins.engsonar.com:5000"' state=present

- name: restart docker
# pending this fix - https://github.com/ansible/ansible-modules-core/issues/1170
#  service: name=docker state=restarted
  shell: service docker restart

- name: destroy the previous web
  docker:
    name: web
    state: absent #stops and then removes any matching containers.
    image: jenkins.engsonar.com:5000/web:latest

- name: pull down and load docker-web
  docker:
    name: web
    hostname: web
    registry: jenkins.engsonar.com:5000
    insecure_registry: true
    image: jenkins.engsonar.com:5000/web:latest
    state: restarted #unconditionally restarts (or starts) the matching containers
    pull: always #the registry will be checked for a newer version of the image' each time the task executes
    ports:
    - "80:80"
    - "443:443"
    command: /sbin/my_init -- sh -c '/etc/my_startup/start_unicorn.sh'
