---
# pull down docker-web and start it

- name: destroy the previous web
  docker:
    name: web
    state: absent #stops and then removes any matching containers.
    image: ec2-52-8-82-197.us-west-1.compute.amazonaws.com:5000/web:latest

- name: pull down and load docker-web
  docker:
    name: web
    hostname: web
    image: ec2-52-8-82-197.us-west-1.compute.amazonaws.com:5000/web:latest
    state: restarted #unconditionally restarts (or starts) the matching containers
    pull: always #the registry will be checked for a newer version of the image' each time the task executes
    ports:
    - "80:80"
    - "443:443"
    command: /sinb/my_init -- sh -c '/etc/my_startup/start_unicorn.sh'
