# ---
# # install docker with yum

# # TODO: specify here which version we should be at and update if it's too old
# # as of time of writing, the current version is 1.6.1
# - name: check for docker
#   shell: docker version
#   register: result
#   ignore_errors: True

# - name: install latest docker with wget
#   shell: wget -qO- https://get.docker.com/ | sh
#   when: result|failed

# - name: add user to docker group
#   user: "name={{ansible_ssh_user}} append=yes groups=docker"
#   # TODO: disconnect after this action so that we can use the permissions in the pull

# # TODO: update yum the first time before running installs

# - name: install python-setuptools
#   yum: name=python-setuptools

# - name: install pip
#   easy_install: name=pip

# - name: install security packages
#   pip: name={{item}}
#   with_items:
#   - pyopenssl
#   - ndg-httpsclient
#   - pyasn1

# # docker version 1.2 changed the variable "docker.client.DEFAULT_DOCKER_API_VERSION" that ansible uses
# # so need to change to 1.1.0 until ansible updates to match
# - name: install docker-py
#   pip: name=docker-py version=1.1.0

